---

- name: update package cache
  ansible.builtin.package:
    update_cache: yes
  become: yes
  when:
    - __systemd_journald_virtualized

- name: install systemd
  ansible.builtin.package:
    name: systemd
    state: present

- name: configure systemd-journald
  ansible.builtin.template:
    src: journald.conf.j2
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  register: __systemd_journald_configuration

- name: enable systemd-journald service and assure it is started
  ansible.builtin.systemd:
    name: systemd-journald
    enabled: yes
    state: >-
      {{
        __systemd_journald_configuration.changed |
          default(False) |
          ternary("restarted", "started")
      }}
  become: yes

...
