---

- name: verify
  hosts: all
  tasks:

    - name: check service
      ansible.builtin.service:
        name: systemd-journald
        enabled: yes
        state: started
      check_mode: yes
      register: __systemd_journald_service

    - name: debug service
      ansible.builtin.debug:
        var: __systemd_journald_service

    - name: assert on service
      ansible.builtin.assert:
        that:
          - not __systemd_journald_service.failed
          - not __systemd_journald_service.changed
          - __systemd_journald_service.state == 'started'
          - __systemd_journald_service.enabled
        success_msg: 'service is both enabled and started'

    - name: check if journalctl works
      ansible.builtin.command: journalctl -n 10
      become: yes
      changed_when: no

...
